#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MovieRandomator")]
	public partial class MRandomatorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMovy(Movy instance);
    partial void UpdateMovy(Movy instance);
    partial void DeleteMovy(Movy instance);
    #endregion
		
		public MRandomatorDataContext() : 
				base(global::ConsoleApplication1.Properties.Settings.Default.MovieRandomatorConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MRandomatorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MRandomatorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MRandomatorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MRandomatorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Movy> Movies
		{
			get
			{
				return this.GetTable<Movy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movies")]
	public partial class Movy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Title;
		
		private int _Year;
		
		private string _Rated;
		
		private string _Released;
		
		private string _Runtime;
		
		private string _Genre;
		
		private string _Director;
		
		private string _Writer;
		
		private string _Actors;
		
		private string _Plot;
		
		private string _Language;
		
		private string _Country;
		
		private string _Awards;
		
		private string _Poster;
		
		private string _Metascore;
		
		private string _imdbRating;
		
		private string _imdbVotes;
		
		private string _Type;
		
		private string _Trailer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnYearChanging(int value);
    partial void OnYearChanged();
    partial void OnRatedChanging(string value);
    partial void OnRatedChanged();
    partial void OnReleasedChanging(string value);
    partial void OnReleasedChanged();
    partial void OnRuntimeChanging(string value);
    partial void OnRuntimeChanged();
    partial void OnGenreChanging(string value);
    partial void OnGenreChanged();
    partial void OnDirectorChanging(string value);
    partial void OnDirectorChanged();
    partial void OnWriterChanging(string value);
    partial void OnWriterChanged();
    partial void OnActorsChanging(string value);
    partial void OnActorsChanged();
    partial void OnPlotChanging(string value);
    partial void OnPlotChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnAwardsChanging(string value);
    partial void OnAwardsChanged();
    partial void OnPosterChanging(string value);
    partial void OnPosterChanged();
    partial void OnMetascoreChanging(string value);
    partial void OnMetascoreChanged();
    partial void OnimdbRatingChanging(string value);
    partial void OnimdbRatingChanged();
    partial void OnimdbVotesChanging(string value);
    partial void OnimdbVotesChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnTrailerChanging(string value);
    partial void OnTrailerChanged();
    #endregion
		
		public Movy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int NOT NULL")]
		public int Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rated", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Rated
		{
			get
			{
				return this._Rated;
			}
			set
			{
				if ((this._Rated != value))
				{
					this.OnRatedChanging(value);
					this.SendPropertyChanging();
					this._Rated = value;
					this.SendPropertyChanged("Rated");
					this.OnRatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Released", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Released
		{
			get
			{
				return this._Released;
			}
			set
			{
				if ((this._Released != value))
				{
					this.OnReleasedChanging(value);
					this.SendPropertyChanging();
					this._Released = value;
					this.SendPropertyChanged("Released");
					this.OnReleasedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Runtime", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Runtime
		{
			get
			{
				return this._Runtime;
			}
			set
			{
				if ((this._Runtime != value))
				{
					this.OnRuntimeChanging(value);
					this.SendPropertyChanging();
					this._Runtime = value;
					this.SendPropertyChanged("Runtime");
					this.OnRuntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Genre
		{
			get
			{
				return this._Genre;
			}
			set
			{
				if ((this._Genre != value))
				{
					this.OnGenreChanging(value);
					this.SendPropertyChanging();
					this._Genre = value;
					this.SendPropertyChanged("Genre");
					this.OnGenreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this.OnDirectorChanging(value);
					this.SendPropertyChanging();
					this._Director = value;
					this.SendPropertyChanged("Director");
					this.OnDirectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Writer", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Writer
		{
			get
			{
				return this._Writer;
			}
			set
			{
				if ((this._Writer != value))
				{
					this.OnWriterChanging(value);
					this.SendPropertyChanging();
					this._Writer = value;
					this.SendPropertyChanged("Writer");
					this.OnWriterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actors", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Actors
		{
			get
			{
				return this._Actors;
			}
			set
			{
				if ((this._Actors != value))
				{
					this.OnActorsChanging(value);
					this.SendPropertyChanging();
					this._Actors = value;
					this.SendPropertyChanged("Actors");
					this.OnActorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plot", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Plot
		{
			get
			{
				return this._Plot;
			}
			set
			{
				if ((this._Plot != value))
				{
					this.OnPlotChanging(value);
					this.SendPropertyChanging();
					this._Plot = value;
					this.SendPropertyChanged("Plot");
					this.OnPlotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Awards", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Awards
		{
			get
			{
				return this._Awards;
			}
			set
			{
				if ((this._Awards != value))
				{
					this.OnAwardsChanging(value);
					this.SendPropertyChanging();
					this._Awards = value;
					this.SendPropertyChanged("Awards");
					this.OnAwardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poster", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Poster
		{
			get
			{
				return this._Poster;
			}
			set
			{
				if ((this._Poster != value))
				{
					this.OnPosterChanging(value);
					this.SendPropertyChanging();
					this._Poster = value;
					this.SendPropertyChanged("Poster");
					this.OnPosterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metascore", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Metascore
		{
			get
			{
				return this._Metascore;
			}
			set
			{
				if ((this._Metascore != value))
				{
					this.OnMetascoreChanging(value);
					this.SendPropertyChanging();
					this._Metascore = value;
					this.SendPropertyChanged("Metascore");
					this.OnMetascoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imdbRating", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string imdbRating
		{
			get
			{
				return this._imdbRating;
			}
			set
			{
				if ((this._imdbRating != value))
				{
					this.OnimdbRatingChanging(value);
					this.SendPropertyChanging();
					this._imdbRating = value;
					this.SendPropertyChanged("imdbRating");
					this.OnimdbRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imdbVotes", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string imdbVotes
		{
			get
			{
				return this._imdbVotes;
			}
			set
			{
				if ((this._imdbVotes != value))
				{
					this.OnimdbVotesChanging(value);
					this.SendPropertyChanging();
					this._imdbVotes = value;
					this.SendPropertyChanged("imdbVotes");
					this.OnimdbVotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Trailer
		{
			get
			{
				return this._Trailer;
			}
			set
			{
				if ((this._Trailer != value))
				{
					this.OnTrailerChanging(value);
					this.SendPropertyChanging();
					this._Trailer = value;
					this.SendPropertyChanged("Trailer");
					this.OnTrailerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
