<?xml version="1.0" encoding="utf-8"?><Database Name="WebApiExampleDB" Class="DataDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=WebApiExampleDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebApiExampleDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Numara" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>